export const sessionData = [
  {
    id: 1,
    title: "System modeling review",
    courseName: "Software Engineering",
    courseID: "CO3001",
    tutorID: 2310846,
    tutor: "Lê Minh Hào",
    startTime: "11:00",
    endTime: "15:00",
    date: "2025-10-10",
    state: "Ongoing",
    location: "B6-305",
    maxStudent: 20,
    students: [
      {studentName: "Nguyen Van A", studentID: 2390000, description: ""},
      {studentName: "Nguyen Van C", studentID: 2390002, description: ""},
      {studentName: "Nguyen Van D", studentID: 2390003, description: ""},
    ],
    description: "- Revise the theory in the System Modeling chapter.\n- Practice drawing Use Case diagrams and writing scenarios.",
    reason: "",
  },
  {
    id: 2,
    title: "Transport layer review",
    courseName: "Computer Networks",
    courseID: "CO3093",
    tutorID: 2310846,
    tutor: "Lê Minh Hào",
    startTime: "14:00",
    endTime: "16:00",
    date: "2025-10-11",
    state: "Not started",
    location: "B9-303",
    maxStudent: 20,
    students: [
      {studentName: "Nguyen Van A", studentID: 2390000, description: ""},
    ],
    description: "",
    reason: "",
  },
  {
    id: 3,
    title: "Weekly meeting",
    courseName: "Software Engineering",
    courseID: "CO3001",
    tutorID: 2310846,
    tutor: "Lê Minh Hào",
    startTime: "21:00",
    endTime: "22:00",
    date: "2025-10-04",
    state: "Being evaluated",
    location: "https://meet.google.com/hpk-iytb-psz",
    maxStudent: 20,
    students: [
      {studentName: "Nguyen Van A", studentID: 2390000, description: ""},
      {studentName: "Nguyen Van B", studentID: 2390001, description: ""},
      {studentName: "Nguyen Van C", studentID: 2390002, description: ""},
      {studentName: "Nguyen Van D", studentID: 2390003, description: ""},
      {studentName: "Nguyen Van E", studentID: 2390004, description: ""},
    ],
    description: "",
    reason: "",
  },
  {
    id: 4,
    title: "Weekly meeting",
    courseName: "Software Engineering",
    courseID: "CO3001",
    tutorID: 2310846,
    tutor: "Lê Minh Hào",
    startTime: "21:00",
    endTime: "22:00",
    date: "2025-09-27",
    state: "Finished",
    location: "https://meet.google.com/hpk-iytb-psz",
    maxStudent: 20,
    students: [
      {studentName: "Nguyen Van A", studentID: 2390000, description: ""},
      {studentName: "Nguyen Van B", studentID: 2390001, description: ""},
      {studentName: "Nguyen Van C", studentID: 2390002, description: ""},
      {studentName: "Nguyen Van D", studentID: 2390003, description: ""},
      {studentName: "Nguyen Van E", studentID: 2390004, description: ""},
    ],
    description: "",
    reason: "",
  },
  {
    id: 5,
    title: "Requirements engineering review",
    courseName: "Software Engineering",
    courseID: "CO3001",
    tutorID: 2310846,
    tutor: "Lê Minh Hào",
    startTime: "11:00",
    endTime: "15:00",
    date: "2025-10-06",
    state: "Canceled",
    location: "B4-302",
    maxStudent: 20,
    students: [
      {studentName: "Nguyen Van A", studentID: 2390000, description: ""},
      {studentName: "Nguyen Van B", studentID: 2390001, description: ""},
      {studentName: "Nguyen Van C", studentID: 2390002, description: ""},
      {studentName: "Nguyen Van D", studentID: 2390003, description: ""},
      {studentName: "Nguyen Van E", studentID: 2390004, description: ""},
    ],
    description: "",
    reason: "",
  },
]